use std::collections::HashMap;

pub struct NextToArrive(pub Vec<HashMap<String, Option<String>>>);
pub struct Arrival(
    pub HashMap<String, Vec<HashMap<String, Vec<HashMap<String, Option<String>>>>>>,
);
pub struct TrainSchedule(pub Vec<HashMap<String, Option<String>>>);

pub struct Stations {
    stations: [&'static str; 154]
}

impl Stations {
    pub fn new() -> Self {
        Stations {
            stations: STATIONS
        }
    }

    pub fn stations(&self) -> &[&'static str; 154] {
        &self.stations
    }

    pub fn exists(&self, entry: &str) -> bool {
        self.stations.contains(&entry)
    }
}

pub const URL: &str = "https://www3.septa.org/api";

const STATIONS: [&'static str; 154] = [
    "9th St",
    "30th Street Station",
    "49th St",
    "Airport Terminal A",
    "airport terminal B",
    "airport terminal C-D",
    "airport terminal E-F",
    "Allegheny",
    "Allen Lane",
    "Ambler",
    "Angora",
    "Ardmore",
    "Ardsley",
    "Aala",
    "Aerwyn",
    "Aethayres",
    "Aridesburg",
    "Aristol",
    "Bryn Mawr",
    "Carpenter",
    "Chalfont",
    "Chelten Avenue",
    "Cheltenham",
    "Chester TC",
    "Chestnut Hill East",
    "Chestnut Hill West",
    "Churchmans Crossing",
    "Claymont",
    "Clifton-Aldan",
    "Colmar",
    "Conshohocken",
    "Cornwells Heights",
    "Crestmont",
    "Croydon",
    "Crum Lynne",
    "Curtis Park",
    "Cynwyd",
    "Darby",
    "Daylesford",
    "Delaware Valley College",
    "Devon",
    "Downingtown",
    "Doylestown",
    "East Falls",
    "Eastwick Station",
    "Eddington",
    "Eddystone",
    "Elkins Park",
    "Elm St",
    "Elwyn Station",
    "Exton",
    "Fern Rock TC",
    "Fernwood",
    "Folcroft",
    "Forest Hills",
    "Ft Washington",
    "Fortuna",
    "Fox Chase",
    "Germantown",
    "Gladstone",
    "Glenside",
    "Gravers",
    "Gwynedd Valley",
    "Hatboro",
    "Haverford",
    "Highland",
    "Highland Ave",
    "Holmesburg Jct",
    "Ivy Ridge",
    "Market East",
    "Jenkintown-Wyncote",
    "Langhorne",
    "Lansdale",
    "Lansdowne",
    "Lawndale",
    "Levittown",
    "Link Belt",
    "Main St",
    "Malvern",
    "Manayunk",
    "Marcus Hook",
    "Meadowbrook",
    "Media",
    "Melrose Park",
    "Merion",
    "Miquon",
    "Morton",
    "Mt Airy",
    "Moylan-Rose Valley",
    "Narberth",
    "Neshaminy Falls",
    "New Britain",
    "Newark",
    "Noble",
    "Norristown TC",
    "North Broad St",
    "North Hills",
    "North Philadelphia",
    "North Wales",
    "Norwood",
    "Olney",
    "Oreland",
    "Overbrook",
    "Paoli",
    "Penllyn",
    "Pennbrook",
    "Penn Medicine Station",
    "Philmont",
    "Primos",
    "Prospect Park",
    "Queen Lane",
    "Radnor",
    "Ridley Park",
    "Rosemont",
    "Roslyn",
    "Rydal",
    "Ryers",
    "Secane",
    "Sedgwick",
    "Sharon Hill",
    "Somerton",
    "Spring Mill",
    "St. Davids",
    "St. Martins",
    "Stenton",
    "Strafford",
    "Suburban Station",
    "Swarthmore",
    "Swarthmore",
    "Tacony",
    "Temple U",
    "Thorndale",
    "Torresdale",
    "Trenton",
    "Trevose",
    "Tulpehocken",
    "Upsal",
    "Villanova",
    "Wallingford",
    "Warminster",
    "Washington Lane",
    "Wayne",
    "Wayne Jct",
    "West Trenton",
    "Whitford",
    "Willow Grove",
    "Wilmington",
    "Wissahickon",
    "Wister",
    "Woodbourne",
    "Wyndmoor",
    "Wynnefield Avenue",
    "Wynnewood",
    "Yardley",
];
